### ISSUE TITLE
Project Idea

### ISSUE THREAD

**Issue by chickenPopcorn** [chickenPopcorn/ASE-Group-Project#1]
The project idea we have is to implement a TinyUrl (I talked to Professor Kaiser, and she green lighted on it). It substitutes a long URL with a short URL like what twitter and google uses. The idea is quiet simple. But we want to take the opportunity to implement it as up to industry standard as possible using the latest dev tools and trends. 

We will use MEAN(MongoDB, Express, Angular.js , Node.js) stack framework also Bootstrap and Redis to develop the project(Just to through some keywords out there so you guys can take a look at them ahead of time). We will automate our test using mocha.js, and selenium(webdriverio) on Travis CI. If we have time we should also consider doing continuous integration and continuous delivery using docker and variety of other tools, since that's something professor talked about in class. Also someone should start a todo list, milestones, labels and deadlines.

Good luck and godspeed.

**Comment by cyrexin** [comment]
Sounds terrific.

**Comment by jiaxinsu2016** [comment]
Sounds good!

**Comment by tiancizhong** [comment]
Sounds great！ ： ）
