### ISSUE TITLE
Add leaderboard

### ISSUE THREAD

**Issue by jiaxinsu2016** [chickenPopcorn/ASE-Group-Project#11]
#56 
Show the most popular URLs.

**Class Name:** 
LeadershipBoard
**Responsibilities:** 
get url info
check url privacy
sort url according to likes
display popular url
**Collaborator:** 
URL

![image](https://cloud.githubusercontent.com/assets/10967669/19785009/d39a7906-9c65-11e6-8cd4-687a10cefa65.png)

**Comment by cyrexin** [comment]
Discussed with Siri, this should be done in the next iteration.
