### ISSUE TITLE
Check long URL correctness

### ISSUE THREAD

**Issue by chickenPopcorn** [chickenPopcorn/ASE-Group-Project#29]
Implementation a function that tests long URL correctness before generating short URL by checking status code.

**Class Name:** 
Validate URL
**Responsibilities**: 
get url
add "http://" before the url
check url redirect to a page
**Collaborator:** 
URL

**Comment by cyrexin** [comment]
If the protocol is missing, now "http://" will be automatically appended.

**Comment by cyrexin** [comment]
Discussed with Siri, the part to validate the URL is still to be done.

**Comment by cyrexin** [comment]
Now it will check if the URL is accessible from the back end.
