### ISSUE TITLE
Add Sign Up

### ISSUE THREAD

**Issue by tiancizhong** [chickenPopcorn/ASE-Group-Project#32]
#23 
**Class Name:** 
Signup
**Responsibilities:** 
get user email
validate user email (not exist before and correct format)
get user password
reenter user password
validate user password
**Collaborator:** 
User info

**Comment by cyrexin** [comment]
Test cases:
- should return status 200 if trying to sign in with the correct combination of username and password
- should return error trying to sign up with the same email
